import Head from 'next/head'

const HeadSeo = ({ title = 'Create Next App', content = 'Generated by create next app' }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={content} />
      <link rel="icon" href="/favicon.ico" />
      <link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet' />
    </Head>
  )
}

export default HeadSeo
