import Head from 'next/head'

const HeadSeo = ({ title = 'Create Next App', content = 'Generated by create next app', favicon }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={content} />
      <link rel="icon" href={favicon ? favicon.data.attributes.url : '/favicon.ico'} />
    </Head>
  )
}

export default HeadSeo
