import Head from 'next/head'
import { HeadSeo, LayoutHome } from '../components/templates'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadSeo title='CEPA | Home' />
      <LayoutHome />
    </div>
  )
}
